# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release_x64)
  proto_math_static_config = release_x64
  proto_math_dynamic_config = release_x64
  proto_math_tests_config = release_x64
endif
ifeq ($(config),debug_x64)
  proto_math_static_config = debug_x64
  proto_math_dynamic_config = debug_x64
  proto_math_tests_config = debug_x64
endif

PROJECTS := proto-math-static proto-math-dynamic proto-math-tests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

proto-math-static:
ifneq (,$(proto_math_static_config))
	@echo "==== Building proto-math-static ($(proto_math_static_config)) ===="
	@${MAKE} --no-print-directory -C . -f proto-math-static.make config=$(proto_math_static_config)
endif

proto-math-dynamic:
ifneq (,$(proto_math_dynamic_config))
	@echo "==== Building proto-math-dynamic ($(proto_math_dynamic_config)) ===="
	@${MAKE} --no-print-directory -C . -f proto-math-dynamic.make config=$(proto_math_dynamic_config)
endif

proto-math-tests: proto-math-static
ifneq (,$(proto_math_tests_config))
	@echo "==== Building proto-math-tests ($(proto_math_tests_config)) ===="
	@${MAKE} --no-print-directory -C . -f proto-math-tests.make config=$(proto_math_tests_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f proto-math-static.make clean
	@${MAKE} --no-print-directory -C . -f proto-math-dynamic.make clean
	@${MAKE} --no-print-directory -C . -f proto-math-tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release_x64"
	@echo "  debug_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   proto-math-static"
	@echo "   proto-math-dynamic"
	@echo "   proto-math-tests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"